### ISSUE TITLE
RDP连接服务器，如果用户名是  .\xxxx 机会报错。

### ISSUE THREAD

**Issue by gywei** [GMYXDS/MstscManager#6]
RDP连接服务器，如果用户名是  .\xxxx 机会报错。

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \y. Path 'user_name', line 1, position 849.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at MstscManager.FMain.connect_serer(Boolean is_temp, String cs_d) in E:\Aprojects\csharp_project\3-MSTSC管理器\源码\MstscManager\MstscManager\FMain.cs:line 901
   at MstscManager.FMain.uiButton7_Click(Object sender, EventArgs e) in E:\Aprojects\csharp_project\3-MSTSC管理器\源码\MstscManager\MstscManager\FMain.cs:line 878
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at Sunny.UI.UIButton.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
MSTSC远程管理器
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
SunnyUI
    程序集版本:3.2.6.1
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq.Expressions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
SunnyUI.Common
    程序集版本:3.2.6.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Console
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Resources.Extensions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Encoding.CodePages
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Data.Sqlite
    程序集版本:6.0.10.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Data.Common
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.RegularExpressions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
SQLitePCLRaw.core
    程序集版本:2.1.2.1721
    Win32 版本:不可用
    代码库:
----------------------------------------
SQLitePCLRaw.batteries_v2
    程序集版本:2.1.2.1721
    Win32 版本:不可用
    代码库:
----------------------------------------
SQLitePCLRaw.provider.e_sqlcipher
    程序集版本:2.1.2.1721
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Ping
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Numerics
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Serialization.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Xml
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:不可用
    代码库:file:///C:/Users/YJ2022070095/Desktop/MstscManager_v1.5_win_x64_withdotnet6/System.Private.CoreLib.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.IO.Compression
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------

************** JIT 调试 **************

**Comment by GMYXDS** [comment]
用户名为.\xxxx， 这个合法吗，mstsc 你能用这个用户名链接上去吗
